services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phonestore
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./phonestore.sql:/docker-entrypoint-initdb.d/phonestore.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p123456"]
      interval: 10s
      retries: 5
      start_period: 240s

  springboot:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/phonestore?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 123456

volumes:
  mysql_data:
