groups:
  - name: app_alerts
    rules:
      - alert: HighMemoryUsage
        expr: node_memory_Active_bytes / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Memory usage is over 90% on {{ $labels.instance }}"

      - alert: HighCpuUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "CPU usage is over 90% on {{ $labels.instance }}"

      - alert: SpringAppDown
        expr: up{job="springboot"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Spring Boot app is down on {{ $labels.instance }}"

      - alert: MySQLDown
        expr: up{job="mysql"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "MySQL database is down on {{ $labels.instance }}"
